desc: Self definition of manifest
elements:
  id: { type: string, desc: Profile identificator }
  desc: { type: string, desc: Description }
  elements:
    type: Map
    desc: Key-Value list of elements
    value:
      elements:
        type:
          desc: Element type
          type: string
          valueset:
            system: data-types
            codes:
              - Map
              - string
              - boolean
              - positiveInt
              - date
              - instant
        desc:
          desc: Element description
          type: string
        req:
          desc: Is this element required?
          type: boolean
        minItems:
          desc: Lower bound of elements in collection
          type: positiveInt
        maxItems:
          desc: Upper bound of elements in collection
          type: positiveInt
        contains:
          desc: Test collection contains pattern
          type: Any
        match:
          desc: Test element match pattern; Used for slicing
          type: Any
        ref:
          desc: Pointer for recursive definition from root of document
          type: string
          coll: true
        valueset:
          desc: Terminology binding
          elements:
            desc: {type: string}
            id:
              desc: valueset id or url
              type: string
            system:
              desc: system for codes or concepts if only one
              type: string
            concepts[]:
              desc: List of concepts
              coll: true
              elements:
                code:
                  req: true
                  desc: Concept code
                  type: string
                system:
                  desc: Concept system; if not present - taken from vs.system
                  type: string
                display:
                  desc: Concept display
                  type: string
        elements:
          ref: [elements,elements]
